//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QnAMakerBot.AgentModule {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConversationText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConversationText() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QnAMakerBot.AgentModule.ConversationText", typeof(ConversationText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 所有客服人員皆在忙線中，請您稍後再試，謝謝 的當地語系化字串。
        /// </summary>
        internal static string AllAgentAreBusy {
            get {
                return ResourceManager.GetString("AllAgentAreBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您已與客服人員結束連線 的當地語系化字串。
        /// </summary>
        internal static string DisconnectWithAgent {
            get {
                return ResourceManager.GetString("DisconnectWithAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請設定 QnAKnowledgebaseId 和 QnASubscriptionKey (請參考 https://qnamaker.ai) 的當地語系化字串。
        /// </summary>
        internal static string NeedQnAMakerSetting {
            get {
                return ResourceManager.GetString("NeedQnAMakerSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您的訊息沒有送給任何人唷... 的當地語系化字串。
        /// </summary>
        internal static string NobodyTalkingToYou {
            get {
                return ResourceManager.GetString("NobodyTalkingToYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您沒有與任何使用者對話 的當地語系化字串。
        /// </summary>
        internal static string NotTalkingWithAnyUser {
            get {
                return ResourceManager.GetString("NotTalkingWithAnyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您沒有與機器人對話 的當地語系化字串。
        /// </summary>
        internal static string NotTalkingWithBot {
            get {
                return ResourceManager.GetString("NotTalkingWithBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 加入這次對話 的當地語系化字串。
        /// </summary>
        internal static string SomeoneJoinTheConversation {
            get {
                return ResourceManager.GetString("SomeoneJoinTheConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您可以繼續和機器人對話 的當地語系化字串。
        /// </summary>
        internal static string StillCanTalkWithBot {
            get {
                return ResourceManager.GetString("StillCanTalkWithBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您已停止對話 的當地語系化字串。
        /// </summary>
        internal static string StopTheConversation {
            get {
                return ResourceManager.GetString("StopTheConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您已與 {0} 完成連線，請開始對話 的當地語系化字串。
        /// </summary>
        internal static string YouConnectToSomeone {
            get {
                return ResourceManager.GetString("YouConnectToSomeone", resourceCulture);
            }
        }
    }
}
